import type { BudgetSimulation } from "@/types/budget";
import type { MatrixItem } from "@/types/matrix";
import type { PurchaseScoreItem } from "@/types/purchaseScore";

export const mockPurchaseScores: PurchaseScoreItem[] = [
  {
    rank: 1,
    brand: "ROLEX",
    model: "サブマリーナー",
    ref_number: "126610LN",
    score: 88,
    turnover_months: 2.1,
    stock_count: 4,
    price_band: "100万円台",
    channel: "auction",
    action: "priority",
  },
  {
    rank: 2,
    brand: "PATEK PHILIPPE",
    model: "ノーチラス",
    ref_number: "5711/1A",
    score: 82,
    turnover_months: 4.5,
    stock_count: 2,
    price_band: "1000万円台",
    channel: "dealer",
    action: "priority",
  },
  {
    rank: 3,
    brand: "ROLEX",
    model: "デイトナ",
    ref_number: "116500LN",
    score: 79,
    turnover_months: 2.8,
    stock_count: 3,
    price_band: "200万円台",
    channel: "auction",
    action: "normal",
  },
  {
    rank: 4,
    brand: "AUDEMARS PIGUET",
    model: "ロイヤルオーク",
    ref_number: "15500ST",
    score: 71,
    turnover_months: 5.2,
    stock_count: 2,
    price_band: "300万円台",
    channel: "dealer",
    action: "normal",
  },
  {
    rank: 5,
    brand: "CARTIER",
    model: "タンク",
    ref_number: "WSTA0052",
    score: 64,
    turnover_months: 6.1,
    stock_count: 7,
    price_band: "50万円台",
    channel: "individual",
    action: "normal",
  },
  {
    rank: 6,
    brand: "OMEGA",
    model: "スピードマスター",
    ref_number: "310.30.42.50.01.002",
    score: 58,
    turnover_months: 7.4,
    stock_count: 9,
    price_band: "50万円台",
    channel: "dealer",
    action: "normal",
  },
  {
    rank: 7,
    brand: "IWC",
    model: "ポルトギーゼ",
    ref_number: "IW371604",
    score: 52,
    turnover_months: 8.2,
    stock_count: 5,
    price_band: "100万円台",
    channel: "auction",
    action: "normal",
  },
  {
    rank: 8,
    brand: "TAG HEUER",
    model: "カレラ",
    ref_number: "CBN2012",
    score: 48,
    turnover_months: 9.0,
    stock_count: 12,
    price_band: "20万円台",
    channel: "individual",
    action: "hold",
  },
  {
    rank: 9,
    brand: "SEIKO",
    model: "グランドセイコー",
    ref_number: "SBGA211",
    score: 44,
    turnover_months: 10.2,
    stock_count: 14,
    price_band: "50万円台",
    channel: "individual",
    action: "hold",
  },
  {
    rank: 10,
    brand: "TUDOR",
    model: "ブラックベイ",
    ref_number: "M7941A1A0RU",
    score: 41,
    turnover_months: 11.5,
    stock_count: 10,
    price_band: "30万円台",
    channel: "dealer",
    action: "hold",
  },
];

export const mockMatrixItems: MatrixItem[] = [
  { brand: "ROLEX", model: "デイトナ", x_turnover: 1.8, y_gross_margin: 24, bubble_size: 6, channel: "auction" },
  { brand: "ROLEX", model: "GMTマスターII", x_turnover: 2.2, y_gross_margin: 21, bubble_size: 5, channel: "dealer" },
  { brand: "PATEK PHILIPPE", model: "ノーチラス", x_turnover: 4.1, y_gross_margin: 26, bubble_size: 2, channel: "auction" },
  { brand: "AUDEMARS PIGUET", model: "ロイヤルオーク", x_turnover: 6.5, y_gross_margin: 9, bubble_size: 2, channel: "auction" },
  { brand: "CARTIER", model: "タンク", x_turnover: 5.2, y_gross_margin: 18, bubble_size: 4, channel: "dealer" },
  { brand: "OMEGA", model: "スピードマスター", x_turnover: 7.8, y_gross_margin: 11, bubble_size: 7, channel: "individual" },
  { brand: "SEIKO", model: "グランドセイコー", x_turnover: 9.4, y_gross_margin: 13, bubble_size: 8, channel: "individual" },
  { brand: "IWC", model: "ビッグパイロット", x_turnover: 5.8, y_gross_margin: 15, bubble_size: 3, channel: "dealer" },
  { brand: "JAEGER", model: "レベルソ", x_turnover: 8.2, y_gross_margin: 16, bubble_size: 3, channel: "dealer" },
  { brand: "BREGUET", model: "トラディション", x_turnover: 10.5, y_gross_margin: 19, bubble_size: 2, channel: "auction" },
  { brand: "PANERAI", model: "ルミノール", x_turnover: 6.9, y_gross_margin: 10, bubble_size: 5, channel: "individual" },
  { brand: "TAG HEUER", model: "モナコ", x_turnover: 11.2, y_gross_margin: 8, bubble_size: 6, channel: "individual" },
  { brand: "TUDOR", model: "ペラゴス", x_turnover: 4.6, y_gross_margin: 14, bubble_size: 5, channel: "dealer" },
  { brand: "ZENITH", model: "クロノマスター", x_turnover: 7.1, y_gross_margin: 12, bubble_size: 4, channel: "auction" },
];

export const mockBudgetSimulation: BudgetSimulation = {
  total_budget: 200_000_000,
  month: "2026-04",
  channels: {
    auction: {
      name: "オークション",
      current_amount: 80_000_000,
      suggested_amount: 95_000_000,
      current_ratio: 40,
      suggested_ratio: 47.5,
      purchase_count: 42,
    },
    dealer: {
      name: "ディーラー",
      current_amount: 90_000_000,
      suggested_amount: 75_000_000,
      current_ratio: 45,
      suggested_ratio: 37.5,
      purchase_count: 28,
      dealers: [
        { name: "JWA", amount: 30_000_000, ratio: 40 },
        { name: "大吉", amount: 35_000_000, ratio: 46.7 },
        { name: "オークネット", amount: 10_000_000, ratio: 13.3 },
      ],
    },
    individual: {
      name: "個人買取",
      current_amount: 30_000_000,
      suggested_amount: 30_000_000,
      current_ratio: 15,
      suggested_ratio: 15,
      purchase_count: 15,
    },
  },
};

export type BrandAllocationRow = {
  id: string;
  name: string;
  ratioPercent: number;
};

/** ブランド配分スライダー用（合計100%想定） */
export const mockBrandAllocationDefaults: BrandAllocationRow[] = [
  { id: "rolex", name: "ROLEX", ratioPercent: 28 },
  { id: "patek", name: "PATEK PHILIPPE", ratioPercent: 18 },
  { id: "ap", name: "AUDEMARS PIGUET", ratioPercent: 14 },
  { id: "cartier", name: "CARTIER", ratioPercent: 12 },
  { id: "others", name: "その他ブランド", ratioPercent: 28 },
];
